# Generated by Django 2.1.1 on 2018-09-09 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180909_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(help_text="Enter book's natural language", max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d046603b-182a-4da8-917b-d19533a902a5'), help_text='Unique ID for this Particular book', primary_key=True, serialize=False),
        ),
    ]
