# Generated by Django 2.1.1 on 2018-09-10 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180909_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(default='Summary of by', help_text='Describe the book in brief', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc7f15da-6d41-42e1-a841-c91a9465d348'), help_text='Unique ID for this Particular book', primary_key=True, serialize=False),
        ),
    ]
