# Generated by Django 2.1.1 on 2018-09-10 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180910_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1403f42f-62b4-4b57-8b6b-d24bcc22f2f5'), help_text='Unique ID for this Particular book', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(default='imp1', max_length=200),
        ),
    ]
