# Generated by Django 2.1.1 on 2018-09-10 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180910_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('586a2d70-a922-4017-a1e9-780a3242fd59'), editable=False, help_text='Unique ID for this Particular book', primary_key=True, serialize=False),
        ),
    ]
