# Generated by Django 2.1.1 on 2018-09-10 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180910_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75a20288-c9a5-4b52-aaf6-ed581a90ff14'), editable=False, help_text='Unique ID for this Particular book', primary_key=True, serialize=False, unique=True),
        ),
    ]
