# Generated by Django 2.1.1 on 2018-09-10 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180910_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1f15e59-563c-42b6-abed-21259547276d'), help_text='Unique ID for this Particular book', primary_key=True, serialize=False, unique=True),
        ),
    ]
